tasks:
  - before: nvm install 14
    init: |
      mkdir my-project
      cp -R examples/magento-graphcms/. my-project
      cd my-project
      jq 'del(.scripts) | with_entries( if .key | contains("scripts_local") then .key |= sub("scripts_local";"scripts") else . end)' package.json > _.json && mv _.json package.json
      cp -R .env.example .env
      rm CHANGELOG.md && touch CHANGELOG.md
      rm -rf node_modules && rm -rf .next
      yarn
      yarn codegen
    command: cd /workspace/graphcommerce/my-project && npm run dev
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - GraphQL.vscode-graphql
    - mikestead.DotENV
    - mrorz.language-gettext
    - Equinusocio.vsc-material-theme
    - Equinusocio.vsc-material-theme-icons
    - IBM.output-colorizer
    - naumovs.color-highlight
    - cschleiden.vscode-github-actions
    - bierner.markdown-preview-github-styles
    - redhat.vscode-yaml
