sources:
  - name: GraphCMS
    handler:
      graphql:
        endpoint: ${GRAPHCMS}
        headers:
          Authorization: ${GRAPHCMS_BEARER}
    transforms:
      - filterSchema:
          - Mutation.createContactForm
