sources:
  - name: GraphCMS
    handler:
      graphql:
        endpoint: ${NEXT_PUBLIC_GRAPHQL}
        headers:
          Authorization: ${NEXT_PUBLIC_GRAPHQL_BEARER}
    transforms:
      - filterSchema:
          - Mutation.createContactForm
