sources:
  - name: algolia
    handler:
      openapi:
        endpoint: 'https://{graphCommerce.algoliaApplicationId}.algolia.net/'
        source: '@graphcommerce/algolia-mesh/algolia-spec.yaml'
        ignoreErrorResponses: true
        schemaHeaders:
          X-Algolia-Application-Id: '{graphCommerce.algoliaApplicationId}'
          X-Algolia-API-Key: '{graphCommerce.algoliaSearchOnlyApiKey}'
        operationHeaders:
          X-Algolia-Application-Id: '{graphCommerce.algoliaApplicationId}'
          X-Algolia-API-Key: '{graphCommerce.algoliaSearchOnlyApiKey}'
        selectQueryOrMutationField:
          - type: Query
            fieldName: searchSingleIndex
    transforms:
      - prefix:
          value: algolia_
          includeRootOperations: true
          includeTypes: false
          mode: bare
      - prefix:
          value: Algolia
          includeRootOperations: false
          includeTypes: true
          mode: bare
additionalResolvers:
  - './mesh/resolvers.ts'
