sources:
  - name: graphcms
    handler:
      graphql:
        useGETForQueries: true
        endpoint: ${GRAPHCMS_URL}
        retry: 3
        operationHeaders:
          gcms-locales: "{context.headers['gcms-locales']}"
    transforms:
      - filterSchema:
          filters:
            - 'Query.*.!locales'
  - name: m2
    handler:
      graphql:
        endpoint: ${MAGENTO_ENDPOINT}
        useGETForQueries: true
        schemaHeaders:
          Store: '{context.headers.store}'
          Authorization: '{context.headers.authorization}'
        operationHeaders:
          Store: '{context.headers.store}'
          Authorization: '{context.headers.authorization}'
          X-ReCaptcha: "{context.headers['x-recaptcha']}"
          Preview-Version: "{context.headers['preview-version']}"
          Content-Currency: "{context.headers['content-currency']}"
  - name: nationaalgeoregister
    handler:
      jsonSchema:
        endpoint: https://geodata.nationaalgeoregister.nl/locatieserver/v3/
        operations:
          - type: Query
            field: nationaalgeoregisterPostcodeService
            path: /free?fq=type:adres&fq=postcode:{args.postcode}&q={args.housenumber}
            method: GET
            responseSample: './lib/address-fields-nl/free.json'
serve:
  playground: true
additionalTypeDefs:
  - './graphql/PostcodeNL.graphqls'
additionalResolvers:
  - './lib/address-fields-nl/nationaalgeoregister.ts'