sources:
  - name: hygraph
    handler:
      graphql:
        useGETForQueries: true
        endpoint: '{graphCommerce.hygraphEndpoint}'
        operationHeaders:
          gcms-locales: "{context.headers['gcms-locales']}"
    transforms:
      - filterSchema:
          filters:
            # Remove mutations: `mutation { * }`
            - 'Mutation.!*'
            # Remove queries: `query { node, row*, asset*, scheduled*, *Version, user* }`
            - 'Query.!{node,asset*,scheduled*,*Version,user*}'
            # Remove field arguments: `query { anyfield(after,before,last,forceParentLocale,locales) { ... } }`
            - '*.*.!{after,before,last,forceParentLocale,locales}'
            # Remove type any input or type fields: `input MyInput {}` or `type MyType { anyfield }`
            - '*.!{localizations,scheduledIn,documentInStages*,createdAt*,updatedAt*,publishedAt*,createdBy,updatedBy,publishedBy,history,scheduledIn*}'
      - prune:
          skipPruning: []

  - name: algolia
    handler:
      openapi:
        endpoint: 'https://l5vhvr29j0.algolia.net/'
        # source: "https://raw.githubusercontent.com/algolia/api-clients-automation/main/specs/search/spec.yml"
        # source: "https://raw.githubusercontent.com/algolia/api-clients-automation/20af70266ff23ac13b76082bb7c0562710442154/specs/bundled/search.yml"
        source: './spec.yaml'
        ignoreErrorResponses: true
        schemaHeaders:
          X-Algolia-Application-Id: '{graphCommerce.algoliaApplicationId}'
          X-Algolia-API-Key: '{graphCommerce.algoliaSearchOnlyApiKey}'
        operationHeaders:
          X-Algolia-Application-Id: '{graphCommerce.algoliaApplicationId}'
          X-Algolia-API-Key: '{graphCommerce.algoliaSearchOnlyApiKey}'
    transforms:
      #  - namingConvention:
      #      mode: bare
      #      typeNames: pascalCase
      #      enumValues: upperCase
      #      fieldNames: camelCase
      #      fieldArgumentNames: camelCase
      - prefix:
          value: algolia_
          includeRootOperations: true
          includeTypes: false
          mode: bare
      - prefix:
          value: Algolia
          includeRootOperations: false
          includeTypes: true
          mode: bare

  - name: m2
    handler:
      graphql:
        endpoint: '{graphCommerce.magentoEndpoint}'
        useGETForQueries: true
        batch: false
        operationHeaders:
          Store: '{context.headers.store}'
          Authorization: '{context.headers.authorization}'
          X-ReCaptcha: "{context.headers['x-recaptcha']}"
          Preview-Version: "{context.headers['preview-version']}"
          Content-Currency: "{context.headers['content-currency']}"
          Engine: '{args.engine}'

additionalResolvers:
  - 'lib/algolia/query/products.ts'
serve:
  playground: true
