sources:
  - name: graphcms
    handler:
      graphql:
        useGETForQueries: true
        endpoint: '{import.meta.graphCommerce.hygraphEndpoint}'
        retry: 3
        operationHeaders:
          gcms-locales: "{context.headers['gcms-locales']}"
    transforms:
      - filterSchema:
          mode: 'bare'
          filters:
            - 'Query.*.!{locales}'
            - 'Mutation.!*'
      - prune:
          skipPruning: []
  - name: m2
    handler:
      graphql:
        endpoint: '{import.meta.graphCommerce.magentoEndpoint}'
        useGETForQueries: true
        schemaHeaders:
          Store: '{context.headers.store}'
          Authorization: '{context.headers.authorization}'
        operationHeaders:
          Store: '{context.headers.store}'
          Authorization: '{context.headers.authorization}'
          X-ReCaptcha: "{context.headers['x-recaptcha']}"
          Preview-Version: "{context.headers['preview-version']}"
          Content-Currency: "{context.headers['content-currency']}"
serve:
  playground: true
