# yaml-language-server: $schema=https://unpkg.com/@graphql-mesh/types@0.49.0/config-schema.json
sources:
  - name: graphcms
    handler:
      graphql:
        endpoint: '${GRAPHCMS_URL}'
    transforms:
      - filterSchema:
          mode: bare
          filters:
            - Query.{pages,footer,usps,productpages,pagesConnection}
            - Mutation.none
  - name: m2
    handler:
      graphql:
        endpoint: '${MAGENTO_ENDPOINT}'
        schemaHeaders:
          Store: '{context.req.headers.store}'
          Authorization: '{context.req.headers.authorization}'
        operationHeaders:
          Store: '{context.req.headers.store}'
          Authorization: '{context.req.headers.authorization}'
