name: bundlesize
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  bundlesize:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          path: new
      - uses: actions/checkout@v4
        with:
          path: old
          ref: ${{ github.base_ref }}
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: '@graphcommerce'
          cache-dependency-path: ./old/yarn.lock
      - run: cd ./new/examples/magento-graphcms && yarn --cwd ./new/examples/magento-graphcms install && cd ../../..
      - run: cd ./new/examples/magento-graphcms && yarn --cwd ./new/examples/magento-graphcms build > new.txt && cd ../../..
      - run: cat ./new/examples/magento-graphcms/new.txt
      - run: cd ./old/examples/magento-graphcms && yarn --cwd ./old/examples/magento-graphcms install && cd ../../..
      - run: cd ./old/examples/magento-graphcms && yarn --cwd ./old/examples/magento-graphcms build > old.txt && cd ../../..
      - run: cat ./new/examples/magento-graphcms/old.txt
      - uses: ho-nl/next-bundlesize-action@master
        id: 'bundlesize'
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.bundlesize.outputs.diff != ''
        with:
          msg: ${{steps.bundlesize.outputs.diff}}
          check_for_duplicate_msg: false
