name: bundlesize
on: [pull_request]
jobs:
  bundlesize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
        with:
          path: new
      - uses: actions/checkout@v2
        with:
          path: old
          ref: master
      - run: yarn --frozen-lockfile --cwd ./new
      - run: yarn --cwd ./new/examples/soxbase build > new.txt
        env:
          NEXT_PUBLIC_GRAPHQL_ENDPOINT: ${{ secrets.NEXT_PUBLIC_GRAPHQL_ENDPOINT }}
          NEXT_PUBLIC_LOCALE_STORES: ${{ secrets.NEXT_PUBLIC_LOCALE_STORES }}
          VERCEL_ENV: development
      - run: cat new.txt
      - run: yarn --frozen-lockfile --cwd ./old
      - run: yarn --cwd ./old/examples/soxbase build > old.txt
        env:
          NEXT_PUBLIC_GRAPHQL_ENDPOINT: ${{ secrets.NEXT_PUBLIC_GRAPHQL_ENDPOINT }}
          NEXT_PUBLIC_LOCALE_STORES: ${{ secrets.NEXT_PUBLIC_LOCALE_STORES }}
          VERCEL_ENV: development
      - run: cat old.txt
      - uses: ho-nl/next-bundlesize-action@master
        id: 'bundlesize'
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{steps.bundlesize.outputs.diff}}
