name: bundlesize
on: [pull_request]
jobs:
  bundlesize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: new
      - uses: actions/checkout@v2
        with:
          path: old
          ref: master
      - run: yarn --frozen-lockfile --cwd ./new
      - run: yarn --cwd ./new build > new.txt
        env:
          GRAPHCMS_BEARER: ${{ secrets.GRAPHCMS_BEARER }}
      - run: cat new.txt
      - run: yarn --frozen-lockfile --cwd ./old
      - run: yarn --cwd ./old build > old.txt
        env:
          GRAPHCMS_BEARER: ${{ secrets.GRAPHCMS_BEARER }}
      - run: cat old.txt
      - uses: ho-nl/next-bundlesize-action@master
        id: 'bundlesize'
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{steps.bundlesize.outputs.diff}}
