name: lighthouse
on: [pull_request]
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - run: npm install -g @lhci/cli@latest
      - id: deployment
        uses: dorshinar/get-deployment-url@v1.0.5
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retryInterval: 2000
      - uses: falnyr/replace-env-vars-action@v1.2.1
        env:
          LHCI_BASE_URL: ${{ steps.deployment.outputs.deployment }} 
        with:
          filename: ./lighthouserc.json
      - run: lhci autorun || echo "failed with errors"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
