name: release
on:
  push:
    branches:
      - 'main'
      - 'canary'
jobs:
  stable:
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
    with:
      releaseScript: release
      releasePrName: Upcoming Release Changes (${{ github.ref }})
      nodeVersion: 16
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}
