name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn --frozen-lockfile
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - run: yarn graphql-codegen -r dotenv/config
        env:
          GRAPHQL: ${{ secrets.GRAPHQL }}
          GRAPHQL_BEARER: ${{ secrets.GRAPHQL_BEARER }}
      - run: yarn storybook-to-ghpages --ci --quiet
        env:
          GH_TOKEN: ho-nl:${{ secrets.GITHUB_TOKEN }}
          GRAPHQL: ${{ secrets.GRAPHQL }}
          GRAPHQL_BEARER: ${{ secrets.GRAPHQL_BEARER }}
