name: windows-build
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  windows-build:
    runs-on: windows-2022
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: '@graphcommerce'
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn --cwd ./examples/magento-graphcms build > windows.txt
      - run: cat new.txt
